import express from 'express';
import {showAllAssignments,getSpecificAssignment,addAssignment,updateAssignment,deleteAssignment} from '../controllers/assignmentController.js';
import {authMiddleware } from '../jwt.js';
const assignmentRouter =express.Router();
assignmentRouter.get("/",authMiddleware,showAllAssignments);
assignmentRouter.get("/:id",authMiddleware,getSpecificAssignment);
assignmentRouter.post("/addassignment",authMiddleware,addAssignment);
assignmentRouter.patch("/:id/updateassignment",authMiddleware,updateAssignment);
assignmentRouter.delete("/:id/deleteassignment",authMiddleware,deleteAssignment);
export default assignmentRouter;